[profile.default]
src = 'src'
out = 'artifacts'
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]